### ISSUE TITLE
No hash_key found in key schema

### ISSUE THREAD

**Issue by jyoost** [pynamodb/PynamoDB#1025]
Every other time I run my code I get this message. every other time it runs fine.

the complete error message:

Traceback (most recent call last):
  File "/home/jyoost/PycharmProjects/fastApiProject/analog_dyno_app/models.py", line 132, in <module>
    part.save()
  File "/home/jyoost/PycharmProjects/fastApiProject/venv/lib/python3.8/site-packages/pynamodb/models.py", line 447, in save
    data = self._get_connection().put_item(*args, **kwargs)
  File "/home/jyoost/PycharmProjects/fastApiProject/venv/lib/python3.8/site-packages/pynamodb/connection/table.py", line 150, in put_item
    return self.connection.put_item(
  File "/home/jyoost/PycharmProjects/fastApiProject/venv/lib/python3.8/site-packages/pynamodb/connection/base.py", line 1011, in put_item
    operation_kwargs = self.get_operation_kwargs(
  File "/home/jyoost/PycharmProjects/fastApiProject/venv/lib/python3.8/site-packages/pynamodb/connection/base.py", line 903, in get_operation_kwargs
    operation_kwargs.update(self.get_identifier_map(table_name, hash_key, range_key, key=key))
  File "/home/jyoost/PycharmProjects/fastApiProject/venv/lib/python3.8/site-packages/pynamodb/connection/base.py", line 823, in get_identifier_map
    return tbl.get_identifier_map(hash_key, range_key=range_key, key=key)
  File "/home/jyoost/PycharmProjects/fastApiProject/venv/lib/python3.8/site-packages/pynamodb/connection/base.py", line 206, in get_identifier_map
    self.hash_keyname: {
  File "/home/jyoost/PycharmProjects/fastApiProject/venv/lib/python3.8/site-packages/pynamodb/connection/base.py", line 102, in hash_keyname
    raise ValueError("No hash_key found in key schema")
ValueError: No hash_key found in key schema

**Comment by ikonst** [comment]
Looks like your model doesn't have a hash key?

**Comment by jyoost** [comment]
I have 2 models they both have hash keys.

**Comment by jyoost** [comment]
I have 2 models they both have hash keys.

**Comment by jyoost** [comment]
I have 2 models they both have hash keys.

**Comment by ikonst** [comment]
Mind sharing some model definitions?
