### ISSUE TITLE
Problem with sharing MapAttribute between a Model and a custom MapAttribute

### ISSUE THREAD

**Issue by divykj** [pynamodb/PynamoDB#1030]
I am trying to share some attributes (`foo` and `bar`) between `SomeModel` and a `CustomMapAttribute`.
I have used inheritance because I didn't want to maintain two separate copies of the attributes list.

I wrote this code:
```python
from pynamodb.attributes import MapAttribute, UnicodeAttribute
from pynamodb.models import Model


class SomeAttrs:
    foo = UnicodeAttribute()
    bar = MapAttribute()


class SomeModel(Model, SomeAttrs):
    pass


class CustomMapAttribute(MapAttribute, SomeAttrs):
    pass


class SomeOtherModel(Model):
    custom_map = CustomMapAttribute()
```

But it fails with:
```python
Traceback (most recent call last):
  File "D:\Path\To\Code\test.py", line 10, in <module>
    class SomeModel(Model, SomeAttrsClass):
  File "C:\Path\To\Python\lib\site-packages\pynamodb\models.py", line 208, in __init__
    super().__init__(name, bases, namespace, discriminator)
  File "C:\Path\To\Python\lib\site-packages\pynamodb\attributes.py", line 240, in __init__
    AttributeContainerMeta._initialize_attributes(self, discriminator)
  File "C:\Path\To\Python\lib\site-packages\pynamodb\attributes.py", line 252, in _initialize_attributes
    if attribute.attr_name != name:
  File "C:\Path\To\Python\lib\site-packages\pynamodb\attributes.py", line 916, in __getattr__      
    raise AttributeError("'{}' has no attribute '{}'".format(self.__class__.__name__, attr))
AttributeError: 'MapAttribute' has no attribute 'attr_name'. Did you mean: 'attr_type'?
```

It works fine when I remove `foo` (`MapAttribute`) from `SomeAttrs` or when I distribute the attrs from `SomeAttrs` into `SomeModel` and `CustomMapAttribute`.

**Comment by divykj** [comment]
Solved it by myself by inheriting `AttributeContainer` in `SomeAttrs`.

```python
from pynamodb.attributes import AttributeContainer

class SomeAttrs(AttributeContainer):
    foo = UnicodeAttribute()
    bar = MapAttribute()
```
