### ISSUE TITLE
exist and does_not_exist condition expression won't work

### ISSUE THREAD

**Issue by sshostak-amplify** [pynamodb/PynamoDB#1062]
Hello!
I got stuck with the conditions and I am pretty sure it is not behaving as supposed. Could you pls check it out?
I am trying to set empty list if attribute attempted_words doesn't exist in table. 
Here are my models:
```
class ResultsModel(Model):
    ....
    item_details = Details(null=True)
    ....
```
```
class Details(MapAttribute):
    ...
    attempted_words = ListAttribute(null=True)

```
This is my code:
```
results = ResultsModel.scan(ResultsModel.measure == 'measure_1')
for result in results:
    result.update(
        condition=(~ResultsModel.item_details.attempted_words[0].exists()),
        actions=[ResultsModel.item_details.attempted_words.set([])]
    )
```
The only way I achieved the result is 
```
~ResultsModel.item_details.attempted_words[0].exists()
```
^ this works when the attempted_words attribute in table is absent and fails if there is data in it. 
also it won't work at all if I put 
`ResultsModel.item_details.attempted_words[0].does_not_exist() `
which supposed to be the same action as ~exists()

When attempted_words list in table is not empty it fails with error:
```
Traceback (most recent call last):
  File "/home/tkali/.local/lib/python3.8/site-packages/pynamodb/connection/base.py", line 992, in update_item
    return self.dispatch(UPDATE_ITEM, operation_kwargs, settings)
  File "/home/tkali/.local/lib/python3.8/site-packages/pynamodb/connection/base.py", line 329, in dispatch
    data = self._make_api_call(operation_name, operation_kwargs, settings)
  File "/home/tkali/.local/lib/python3.8/site-packages/pynamodb/connection/base.py", line 440, in _make_api_call
    raise VerboseClientError(botocore_expected_format, operation_name, verbose_properties)
pynamodb.exceptions.VerboseClientError: An error occurred (ConditionalCheckFailedException) on request (4HHK5E8GS1CUBBAN0C7SG0T88NVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (Name of my table) when calling the UpdateItem operation: The conditional request failed
​
During handling of the above exception, another exception occurred:
​
Traceback (most recent call last):
  File "main.py", line 79, in <module>
    main()
  File "/home/tkali/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/tkali/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/tkali/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tkali/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "main.py", line 75, in main
    update_result(result)
  File "main.py", line 32, in update_result
    result.update(
  File "/home/tkali/.local/lib/python3.8/site-packages/pynamodb/models.py", line 433, in update
    data = self._get_connection().update_item(hk_value, range_key=rk_value, return_values=ALL_NEW, condition=condition, actions=actions, settings=settings)
  File "/home/tkali/.local/lib/python3.8/site-packages/pynamodb/connection/table.py", line 124, in update_item
    return self.connection.update_item(
  File "/home/tkali/.local/lib/python3.8/site-packages/pynamodb/connection/base.py", line 994, in update_item
    raise UpdateError("Failed to update item: {}".format(e), e)
pynamodb.exceptions.UpdateError: Failed to update item: An error occurred (ConditionalCheckFailedException) on request (4HHK5E8GS1CUBBAN0C7SG0T88NVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (Name of my table) when calling the UpdateItem operation: The conditional request failed
```

**Comment by ikonst** [comment]
Try:
```python
from pynamodb.expressions.condition import size

...
result.update(
    condition=size(ResultsModel.item_details.attempted_words) == 0,
    ...
)
```

If you want to handle both empty and non-existing lists:
```python
result.update(
    condition=(size(ResultsModel.item_details.attempted_words) == 0) | ResultsModel.item_details.does_not_exist(),
    ...
)
```

**Comment by sshostak-amplify** [comment]
Thanks for reply, Ilya! 
The last condition you mentioned works when attempted_words doesn't exist or it is empty. 
And still fails though with the same error when attempted_words list is not empty.
Any thoughts?

**Comment by ikonst** [comment]
What would you want to happen in that case? Have the `update` not do anything but also return no error?

**Comment by sshostak-amplify** [comment]
I'd say not doing anything. Ideally we expect it not to fail and skip update action in case there are any values inside already. 
I added work-around with the if-statement like
`if not result.item_details.attribute_values.get("attempted_words")`
but still wonder if that is possible to be done with condition attribute

**Comment by sshostak-amplify** [comment]
Looks not so obvious but that worked. Thanks for your help! 
God bless open source.
