### ISSUE TITLE
Item update does not raise ModelInstance.DoesNotExist

### ISSUE THREAD

**Issue by estyxx** [pynamodb/PynamoDB#1072]
If the object does not exist in DynamoDB I would expect the update operation to fail and raise `ModelInstance.DoesNotExist`, instead it is saving the item into the database. 

Here there is an example to reproduce: 
```python
import uuid

from pynamodb.attributes import UnicodeAttribute
from pynamodb.models import Model
from pynamodb_attributes import UUIDAttribute


class Book(Model):
    class Meta:
        table_name = "books"

    id = UUIDAttribute(hash_key=True)
    title = UnicodeAttribute()
    
id = uuid.uuid4()
# >>> id
# UUID('b3e20e41-0fa3-4068-acf4-d968ca95d48d')
Book.get(id)
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/usr/local/lib/python3.10/site-packages/pynamodb/models.py", line 551, in get
#    raise cls.DoesNotExist()
# Book.DoesNotExist: None
b = Book(id=id, title="fake1234")
Book.get(id)
# Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/usr/local/lib/python3.10/site-packages/pynamodb/models.py", line 551, in get
#    raise cls.DoesNotExist()
#Book.DoesNotExist: None
b.update(actions=[Book.title.set("real5678")])
# {'Attributes': {'title': {'S': 'real5678'}, 'id': {'S': 'b3e20e41-0fa3-4068-acf4-d968ca95d48d'}}, 'ConsumedCapacity': #{'TableName': 'books', 'CapacityUnits': 1.0}}
Book.get(id)
# books<b3e20e41-0fa3-4068-acf4-d968ca95d48d>
```

**Comment by ikonst** [comment]
`update` wraps UpdateItem without changing its semantics. The [docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html) say:
> Edits an existing item's attributes, or adds a new item to the table if it does not already exist.

You can add `condition=Book.id.does_not_exist()` to prevent this.
