### ISSUE TITLE
Boto -Describe Table 5.2.2

### ISSUE THREAD

**Issue by avatar296** [pynamodb/PynamoDB#1086]
I'm getting this after installing the 5.2.2 patch.  The endpoint_url issue seems to be fixed but this cropped up.

[ERROR] TypeError: Cannot mix str and non-str arguments
Traceback (most recent call last):
  File "/opt/python/aws_lambda_powertools/tracing/tracer.py", line 305, in decorate
    response = lambda_handler(event, context, **kwargs)
  File "/opt/python/aws_lambda_powertools/middleware_factory/factory.py", line 134, in wrapper
    response = middleware()
  File "/opt/python/aws_lambda_powertools/utilities/data_classes/event_source.py", line 39, in event_source
    return handler(data_class(event), context)
  File "/var/task/event_handler.py", line 34, in lambda_handler
    domain_mgr.calculate_metrics(_data["pk"]["S"], _data["sk"]["S"])
  File "/var/task/domain/hex_manager.py", line 39, in calculate_metrics
    self.applications = self.metric_raw_repo.get_dealer_applications(dealer_id)
  File "/var/task/adapters/out/raw_ddb_repo.py", line 49, in get_dealer_applications
    for _application in _MetricRawModel.data_index.query(
  File "/var/task/pynamodb/pagination.py", line 194, in __next__
    self._get_next_page()
  File "/var/task/pynamodb/pagination.py", line 179, in _get_next_page
    page = next(self.page_iter)
  File "/var/task/pynamodb/pagination.py", line 115, in __next__
    page = self._operation(*self._args, settings=self._settings, **self._kwargs)
  File "/var/task/pynamodb/connection/table.py", line 270, in query
    return self.connection.query(
  File "/var/task/pynamodb/connection/base.py", line 1295, in query
    tbl = self.get_meta_table(table_name)
  File "/var/task/pynamodb/connection/base.py", line 555, in get_meta_table
    data = self.dispatch(DESCRIBE_TABLE, operation_kwargs)
  File "/var/task/pynamodb/connection/base.py", line 332, in dispatch
    data = self._make_api_call(operation_name, operation_kwargs, settings)
  File "/var/task/pynamodb/connection/base.py", line 361, in _make_api_call
    request_dict = self.client._convert_to_request_dict(
  File "/var/task/botocore/client.py", line 984, in _convert_to_request_dict
    prepare_request_dict(
  File "/var/task/botocore/awsrequest.py", line 270, in prepare_request_dict
    url = _urljoin(endpoint_url, r['url_path'], host_prefix)
  File "/var/task/botocore/awsrequest.py", line 336, in _urljoin
    reconstructed = urlunsplit((p[0], new_netloc, new_path, p[3], p[4]))
  File "/var/lang/lib/python3.9/urllib/parse.py", line 512, in urlunsplit
    _coerce_args(*components))
  File "/var/lang/lib/python3.9/urllib/parse.py", line 125, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")

**Comment by avatar296** [comment]
dupe
