### ISSUE TITLE
"Failed to query items: Unable to locate credentials" when connecting to DynamoDB Local

### ISSUE THREAD

**Issue by pzelnip** [pynamodb/PynamoDB#1229]
According to https://pynamodb.readthedocs.io/en/stable/local.html connecting Pynamo to DynamoDB local is supported.  I have DynamoDB local running via Docker on port 9000:

```
docker run -p 9000:8000 -d amazon/dynamodb-local
```

Doing a docker ps shows it running:

```
$ docker ps
CONTAINER ID   IMAGE                        COMMAND                  CREATED         STATUS                 PORTS                                                                                                         NAMES
6e229cad3599   amazon/dynamodb-local        "java -jar DynamoDBL…"   2 minutes ago   Up 2 minutes           0.0.0.0:9000->8000/tcp                                                                                        stoic_brahmagupta
```

Yet all operations through Pynamo seem to be failing with an "Unable to locate credentials" error.  Minimal example:

```
from datetime import datetime
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, UTCDateTimeAttribute

class BaseModel(Model):
    partition_key = UnicodeAttribute(hash_key=True, attr_name="pk")
    sort_key = UnicodeAttribute(range_key=True, attr_name="sk")
    created_at = UTCDateTimeAttribute(default_for_new=datetime.utcnow)
    updated_at = UTCDateTimeAttribute(default=datetime.utcnow)
    class Meta:
        table_name = 'test_table'
        host = "http://localhost:9000"

BaseModel.create_table()
```

Upon executing this in a Python REPL I get:

```
>>> BaseModel.create_table()
Traceback (most recent call last):
  File "/Users/adamparkin/temp/sandbox/.venv/lib/python3.10/site-packages/pynamodb/connection/base.py", line 801, in describe_table
    data = self.dispatch(DESCRIBE_TABLE, operation_kwargs)
  File "/Users/adamparkin/temp/sandbox/.venv/lib/python3.10/site-packages/pynamodb/connection/base.py", line 347, in dispatch
    data = self._make_api_call(operation_name, operation_kwargs, settings)
  File "/Users/adamparkin/temp/sandbox/.venv/lib/python3.10/site-packages/pynamodb/connection/base.py", line 415, in _make_api_call
    prepared_request = self._create_prepared_request(request_dict, settings)
  File "/Users/adamparkin/temp/sandbox/.venv/lib/python3.10/site-packages/pynamodb/connection/base.py", line 324, in _create_prepared_request
    self._sign_request(request)
  File "/Users/adamparkin/temp/sandbox/.venv/lib/python3.10/site-packages/pynamodb/connection/base.py", line 316, in _sign_request
    auth.add_auth(request)
  File "/Users/adamparkin/temp/sandbox/.venv/lib/python3.10/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adamparkin/temp/sandbox/.venv/lib/python3.10/site-packages/pynamodb/models.py", line 811, in create_table
    if not cls.exists():
  File "/Users/adamparkin/temp/sandbox/.venv/lib/python3.10/site-packages/pynamodb/models.py", line 775, in exists
    cls._get_connection().describe_table()
  File "/Users/adamparkin/temp/sandbox/.venv/lib/python3.10/site-packages/pynamodb/connection/table.py", line 293, in describe_table
    return self.connection.describe_table(self.table_name)
  File "/Users/adamparkin/temp/sandbox/.venv/lib/python3.10/site-packages/pynamodb/connection/base.py", line 811, in describe_table
    raise TableError("Unable to describe table: {}".format(e), e)
pynamodb.exceptions.TableError: Unable to describe table: Unable to locate credentials
```

This in a Python 3.10.12 venv, with pynamodb 5.5.1 installed.

Any ideas?  How would I specify credentials for local Dynamo?

**Comment by pzelnip** [comment]
Figured it out, had to export `AWS_ACCESS_KEY` and `AWS_SECRET_ACCESS_KEY` variables (the actual values don't seem to matter?)

```
export AWS_ACCESS_KEY=test
export AWS_SECRET_ACCESS_KEY=test
```

After that could connect.
