### ISSUE TITLE
get_attributes() raises AttributeError on Office example

### ISSUE THREAD

**Issue by jkirsch-patreon** [pynamodb/PynamoDB#1259]
Using the [office model from examples](https://github.com/pynamodb/PynamoDB/blob/master/examples/office_model.py), `Office.get_attributes()` raises an AttributeError exception.

```
>>> Office.get_attributes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dev/patreon_py/venv/lib/python3.9/site-packages/pynamodb/attributes.py", line 554, in __repr__
    fields = ', '.join(f'{k}={v!r}' for k, v in self.attribute_values.items())
  File "/home/dev/patreon_py/venv/lib/python3.9/site-packages/pynamodb/attributes.py", line 1095, in __getattr__
    raise AttributeError("'{}' has no attribute '{}'".format(self.__class__.__name__, attr))
AttributeError: 'Location' has no attribute 'attribute_values'
```

**Comment by jkirsch-patreon** [comment]
But `Thread.get_attributes()` from examples does not. I believe it is due to attributes of Office which are subclass of MapAttribute
