### ISSUE TITLE
Do you know about this error "SysCallError: (32, 'EPIPE')"?

### ISSUE THREAD

**Issue by prince-tanapong** [pynamodb/PynamoDB#138]
```
Internal Server Error: /calls/api/
Traceback (most recent call last):
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/local/lib/python2.7/site-packages/newrelic-2.18.1.15/newrelic/hooks/framework_django.py", line 492, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/local/lib/python2.7/site-packages/newrelic-2.18.1.15/newrelic/hooks/framework_django.py", line 829, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "./insights/views.py", line 7577, in get
    if not DynamoCallSession.exists():
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/pynamodb/models.py", line 641, in exists
    cls._get_connection().describe_table()
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/pynamodb/connection/table.py", line 181, in describe_table
    return self.connection.describe_table(self.table_name)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/pynamodb/connection/base.py", line 409, in describe_table
    tbl = self.get_meta_table(table_name, refresh=True)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/pynamodb/connection/base.py", line 263, in get_meta_table
    data = self.dispatch(DESCRIBE_TABLE, operation_kwargs)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/pynamodb/connection/base.py", line 221, in dispatch
    data = method(**operation_kwargs)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/botocore/client.py", line 269, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/botocore/client.py", line 312, in _make_api_call
    operation_model, request_dict)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/botocore/endpoint.py", line 110, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/botocore/endpoint.py", line 139, in _send_request
    success_response, exception):
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/botocore/endpoint.py", line 203, in _needs_retry
    caught_exception=caught_exception)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/home/deployer/.virtualenvs/pronto-dashboard-env/lib/python2.7/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
SysCallError: (32, 'EPIPE')
```

**Comment by danielhochman** [comment]
How often are you seeing this error?

I found some information about it here: https://github.com/boto/boto3/issues/220

It may be that we need to update the version of requests we're using by way of upgrading botocore since we use its vendored version.

**Comment by danielhochman** [comment]
Also what version of pynamodb are you running?

**Comment by princepronto** [comment]
Does not often but it impact our data. By the way we use pynamo version 1.4.2

**Comment by joshowen** [comment]
I've monkey patched botocore to handle this.  I also monkey patch pynamodb to use the latest botocore that I have installed (non-vendored)
```

    from requests.exceptions import ConnectionError, SSLError, ConnectTimeout, Timeout
    from requests.packages.urllib3.exceptions import ClosedPoolError
    from OpenSSL.SSL import SysCallError
    import botocore.retryhandler
    botocore.retryhandler.EXCEPTION_MAP['GENERAL_CONNECTION_ERROR'].extend((SysCallError, SSLError, ConnectionError, ConnectTimeout,
                                                                            Timeout, ClosedPoolError, TypeError))
```

**Comment by princepronto** [comment]
I don't understand. Can you explain more how to fix this. What file in
pynamo or botocore that I have to fix.

I have a lot of error in this time.

Thank you sir.

**Comment by jpinner-lyft** [comment]
botocore disabled support of PyOpenSSL in https://github.com/boto/botocore/pull/803
using to botocore >= 1.4.0 to fix this issue
