### ISSUE TITLE
Time To Live (TTL) support?

### ISSUE THREAD

**Issue by Bartvds** [pynamodb/PynamoDB#259]
Would be cool if we could set Time To Live (TTL) in the Meta options:

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html

**Comment by brandond** [comment]
This has the potential to be a major work saver. Will take a look at what this would take to implement.

There is a fairly major caveat on TTL support:
>**Important**
> DynamoDB typically deletes expired items within 48 hours of expiration. The exact duration within which an item truly gets deleted after expiration is specific to the nature of the workload and the size of the table. Items that have expired and not been deleted will still show up in reads, queries, and scans.
>
> Due to the potential delay between expiration and deletion time, you might get expired items when you query for items. If you don’t need to view expired items when you issue a read request, you should filter out the expired items using the expiration attribute that you have defined.
>
>You can do this by using a filter expression that returns only items where the Time To Live expiration value is greater than the current time in epoch format.

**Comment by brandond** [comment]
I will also note that while it would seen make the most sense to integrate this into the `UTCDateTimeAttribute` class, that unfortunately stores things as a ISO8601 string, while TTL support requires a numeric field containing an epoch timestamp.

**Comment by Bartvds** [comment]
Thanks for the caveat; the TTL is mostly about limiting table growth for cache/session type data so the 48 hr limbo should be fine if noted in the docs of the attribute.

**Comment by brandond** [comment]
Hey @Bartvds, can you check out #355 and see if this works for you?

**Comment by Bartvds** [comment]
@brandond thanks for working on this. This issue was a bit older so I don't have the use-case anymore, but I did a quick test in a blank project.

I took the last commit in #355  (2e7710b56cef97c1f673d8155e7f030345d4539b) and inserted a bunch of instances with TTL's for next 72 hours:

````python
expire = datetime.now()

for i in range(1, 72):
    item = TestModel(
        foo='foo_{:04d}'.format(i),
        bar='bar',
        expire=expire + timedelta(hours=i),
    )
    item.save()
````

They show up in the Amazon DynamoDB console, the expire field is labelled as  'Expire (TTL)' and I see a 'Time to Live (TTL)' metric so that's hopeful.

But when I try to iterate over the items (so I can see items disappear later) I get this error:

````python
for item in TestModel.scan():
    print(item) 
````

````
Traceback (most recent call last):
  File "./main.py", line 44, in <module>
    for item in TestModel.scan():
  File "/home/vagrant/.virtualenvs/pynamo-test/src/pynamodb/pynamodb/models.py", line 808, in scan
    yield cls.from_raw_data(item)
  File "/home/vagrant/.virtualenvs/pynamo-test/src/pynamodb/pynamodb/models.py", line 519, in from_raw_data
    kwargs[attr_name] = attr.deserialize(attr.get_value(value))
  File "/home/vagrant/.virtualenvs/pynamo-test/src/pynamodb/pynamodb/attributes.py", line 565, in get_value
    value_to_deserialize = super(LegacyUTCDateTimeAttribute, self).get_value(value)
TypeError: super(type, obj): obj must be an instance or subtype of type
````

Also I note that `TestModel.count()` gives 0 (zero) as result, while I see items in the console.

**Comment by brandond** [comment]
Looks like a copy-paste error in the new class. Good catch, I'm curious why it didn't turn up in the test suite. Should be easy to fix.

**Comment by brandond** [comment]
OK, should be fixed now. Also, I think you want `datetime.utcnow()`, not `datetime.now()`. You should be able to repeat your test with that modification. I am seeing that things are removed well before 48 hours, but not immediately. I'm guessing there's a background job that runs periodically, with the frequency dependent on table size and unused capacity.

**Comment by Bartvds** [comment]
Cool, thanks. I'm so used to Django's `timezone.now()` I always forget this vanilla `datetime.now()` isn't UTC , I'm +2:00 TZ so it's not that huge difference overnight.

I did see my test table was culled a bit, it only had 54 of 71 items and the TTL graph in the Metrics panel shows an item removed every hour. We'll have to experiment a bit how that goes in practice.

Also I re-ran the script with your latest commit from the PR (a5ed2c22) and it runs fine now, 71 items replace the previous ones.

What is curious though is how the DyanomoDB console says I have 71 items now, and scan `len(list(TestModel.scan())))` indeed returns 71 items, but `TestModel.count()` (and `TestModel.count(consistent_read=True)` also) still say 54 items. Maybe this is part of DynamoDB's murky consistency/count? I'll have t

**Comment by Bartvds** [comment]
It's a few hours later now, and the count has updated to 71 so that's cool, except meanwhile the first 2 items got expired and culled, so it actually only has 69 items in the scan. 

Another thing I noted while googling on this is how most examples and docs have an integer amount of seconds as expire value, while in this version of your PR I see fractions in my table. (their own code example for python uses `import time; long(time.time())`.

**Comment by brandond** [comment]
The only constraint on TTL is that the field has to be a Number, which is essentially a fixed-precision (decimal) type. Given that it lazily expires things, there's probably not a ton of value in storing timestamps with sub-second precision - but if you want to, DynamoDB won't stop you.

```
Number
Numbers can be positive, negative, or zero. Numbers can have up to 38 digits precision. Exceeding this results in an exception.
    Positive range: 1E-130 to 9.9999999999999999999999999999999999999E+125
    Negative range: -9.9999999999999999999999999999999999999E+125 to -1E-130
In DynamoDB, numbers are represented as variable length. Leading and trailing zeroes are trimmed.
```

**Comment by dmulter** [comment]
Looking forward to this, thanks for the work!

**Comment by brandond** [comment]
PR should be ready...

**Comment by cantoniazzi** [comment]
Had this feature was implemented?

**Comment by cantoniazzi** [comment]
@brandond thanks to answer me! So, how do you do to setup TTL in the registers of your Dynamo registers?

**Comment by brandond** [comment]
@cantoniazzi if you're using this patch, just set `ttl=True` on one of your attributes. See https://github.com/pynamodb/PynamoDB/issues/259#issuecomment-330392601 for an example. If you want to enable this on a table (Model) that already exists, you'll need to do `TestModel.update_table()` in order to sync the table attributes (throughput, ttl, etc) back into DynamoDB.

**Comment by dmulter** [comment]
Would love to see this in a release. I'm fine with the UTCDateTimeAttribute class approach.

**Comment by brandond** [comment]
I just rebased this to master; I haven't had a chance to switch it over to using a new DateTime class instead of replacing the existing class with a different serialization format.

**Comment by keithjjones** [comment]
I didn't see this change in master.  Did I miss it somewhere?

**Comment by techdragon** [comment]
Is there a reason this cant be merged as it stands currently?

**Comment by ikonst** [comment]
@techdragon this is an issue, not a pull request

**Comment by techdragon** [comment]
Sorry, @ikonst it looks like I got my wires crossed, I was talking about https://github.com/pynamodb/PynamoDB/pull/355, which now I look deeper, has some conflicts still open, but work still progressing. So all its well with the world. :-)

**Comment by ikonst** [comment]
FWIW, if you don't use PynamoDB to create your tables, a practice I'd eschew in favor of a provisioning tool like Terraform, then you can use TTLs right now — simply create an `IntegerAttribute` with a name matching your TTL configuration, and assign it a Unix epoch timestamp of the expiry time.

**Comment by canepan** [comment]
Will this be added to the docs, too?
I was looking [there](https://pynamodb.readthedocs.io/en/latest/index.html), and I couldn't find it, except then I did a search and it turns out it's actually implemented
