### ISSUE TITLE
ValueError: Circular reference detected

### ISSUE THREAD

**Issue by rschmidtz** [pynamodb/PynamoDB#350]
I'm having the following error: `ValueError: Circular reference detected` when I try to fetch some items

## **Steps to reproduce the error**

DynamoDB Model:

```
class ProductModel(Model):
    class Meta:
        table_name = 'catalogo'

    id = UnicodeAttribute(hash_key=True)
    name = UnicodeAttribute(null=False)
    price = UnicodeAttribute(null=False)
```

 I can create items without any problem

```
add_product = ProductModel(id=item_id,name="name", price="theprice")
add_product.save()
```

Then I fetch the item by the hash_key id

```
def get_item(id):
    item_get = ProductModel.get(id)
    return item_get
```
The previous function return:

`Traceback (most recent call last):
File "/var/lang/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/var/lang/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/var/lang/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
`

**Comment by jpinner-lyft** [comment]
@rschmidtz I'm having difficulty reproducing the issue -- what version of pynamodb are you using?
