### ISSUE TITLE
create_table fails when using hash_key=True

### ISSUE THREAD

**Issue by bendog** [pynamodb/PynamoDB#356]
using pynamodb==3.1.0

my model
```python
class Topic(models.Model):
    topic = attributes.UnicodeAttribute(hash_key=True)
    votes = attributes.NumberAttribute(default=1)
    last_vote = attributes.UTCDateTimeAttribute(datetime.now)

    class Meta:
        table_name = 'Topic'
        region = 'ap-southeast-2'
```

will cause this error.

```
>>> Topic.create_table(read_capacity_units=1, write_capacity_units=1, wait=True)

Traceback (most recent call last):
  File "/Users/ben.fitz/.virtualenvs/pdpd201710/lib/python3.6/site-packages/pynamodb/connection/base.py", line 528, in create_table
    data = self.dispatch(CREATE_TABLE, operation_kwargs)
  File "/Users/ben.fitz/.virtualenvs/pdpd201710/lib/python3.6/site-packages/pynamodb/connection/base.py", line 271, in dispatch
    data = self._make_api_call(operation_name, operation_kwargs)
  File "/Users/ben.fitz/.virtualenvs/pdpd201710/lib/python3.6/site-packages/pynamodb/connection/base.py", line 349, in _make_api_call
    raise VerboseClientError(botocore_expected_format, operation_name, verbose_properties)
pynamodb.exceptions.VerboseClientError: An error occurred (ValidationException) on request (1S08BEC918IQ3U0AA52OFKEHVBVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (Topic) when calling the CreateTable operation: Invalid KeySchema: The second KeySchemaElement is not a RANGE key type
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/ben.fitz/.virtualenvs/pdpd201710/lib/python3.6/site-packages/pynamodb/models.py", line 864, in create_table
    **schema
  File "/Users/ben.fitz/.virtualenvs/pdpd201710/lib/python3.6/site-packages/pynamodb/connection/table.py", line 270, in create_table
    stream_specification=stream_specification
  File "/Users/ben.fitz/.virtualenvs/pdpd201710/lib/python3.6/site-packages/pynamodb/connection/base.py", line 530, in create_table
    raise TableError("Failed to create table: {0}".format(e), e)
pynamodb.exceptions.TableError: Failed to create table: An error occurred (ValidationException) on request (1S08BEC918IQ3U0AA52OFKEHVBVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (Topic) when calling the CreateTable operation: Invalid KeySchema: The second KeySchemaElement is not a RANGE key type
```

hoever if i use this invalid model specification
```python
class Topic(models.Model):
    topic = attributes.UnicodeAttribute(range_key=True)
    votes = attributes.NumberAttribute(default=1)
    last_vote = attributes.UTCDateTimeAttribute(datetime.now)

    class Meta:
        table_name = 'Topic'
        region = 'ap-southeast-2'
```

it works.

why isn't the table creation method using my hash_key=True setting?

**Comment by jpinner-lyft** [comment]
@bendog in the definition of your `last_vote` attribute you are missing the `default=` keyword argument. The result is that python is assigning `datetime.now` to the `hash_key` argument.

Your first example fails because you are declaring a model with two hash keys (`topic` and `last_vote`). Your second succeeds because you are declaring a model with a String-type hash key (`last_vote`) and range key (`topic`).

**Comment by bendog** [comment]
thanks @jpinner-lyft
