### ISSUE TITLE
Deserialization of model with MapAttribute requires all attributes to be declared

### ISSUE THREAD

**Issue by mathewmarcus** [pynamodb/PynamoDB#358]
Currently, when a model is deserialized, any attributes which are not declared as attributes of the model are simply ignored. However, this is not the case for `MapAttribute`s. If the DynamoDB table has nested attributes within an `'M'` type attribute which are not represented in the corresponding `pynamodb.attributes.MapAttribute` subclass, an `AttributeError` is raised.

**Steps to reproduce**
``` python
from pynamodb.models import Model
from pynamodb.attributes import MapAttribute, NumberAttribute, UnicodeAttribute
from boto3 import resource
from decimal import Decimal


class Location(MapAttribute):
    lat = NumberAttribute()
    lng = NumberAttribute()
    name = UnicodeAttribute()

class Office(Model):
    class Meta:
        table_name = 'OfficeModel'
        host = "http://localhost:8000"

    office_id = NumberAttribute(hash_key=True)
    address = Location()

if not Office.exists():
    Office.create_table(read_capacity_units=1, write_capacity_units=1)

loc = Location(lat=-0.48591, lng=62.26732, name='MyLocation')
office = Office(office_id=123, address=loc)
office.save()

table = resource('dynamodb', endpoint_url='http://localhost:8000').Table('OfficeModel')
modified_office = {
    u'office_id': Decimal('123'),
    u'address': {
        u'foo': 'bar',
        u'latitude': Decimal('-0.48591'),
        u'name': u'MyLocation',
        u'longitude': Decimal('62.26732')
    }
}
table.put_item(TableName='OfficeModel', Item=modified_office)
x = list(Office.scan())
```
This raises the following error
```
Traceback (most recent call last):                                                                                      
  File "mapattribute.py", line 39, in <module>                                                                          
    x = list(Office.scan())                                                                                             
  File "/home/foo/.virtualenvs/pynamodb/lib/python2.7/site-packages/pynamodb/models.py", line 780, in  
scan                                                                                                                    
    yield cls.from_raw_data(item)                                                                                       
  File "/home/foo/.virtualenvs/pynamodb/lib/python2.7/site-packages/pynamodb/models.py", line 509, in  
from_raw_data                                                                                                           
    kwargs[attr_name] = attr.deserialize(attr.get_value(value))                                                         
  File "/home/foo/.virtualenvs/pynamodb/lib/python2.7/site-packages/pynamodb/attributes.py", line 511, 
 in deserialize                                                                                                         
    deserialized_value = attr_class.deserialize(attr_value)
AttributeError: 'NoneType' object has no attribute 'deserialize'
```

The only way to avoid this error is to explicitly declare each attribute in the `MapAttribute` subclass.
``` python
class Location(MapAttribute):
    lat = NumberAttribute()
    lng = NumberAttribute()
    name = UnicodeAttribute()
    foo = NullAttribute()
```
Ideally, in order to facilitate flexible `MapAttribute`s, additional, undeclared attributes would be ignored as they are in `Model`s.

**Comment by mathewmarcus** [comment]
Sorry, didn't mean to close this.

**Comment by mathewmarcus** [comment]
I see that this is milestone, just wanted to point out that there is an open pull request for it.
