### ISSUE TITLE
casting for MapAttribute of MapAttribute

### ISSUE THREAD

**Issue by jney** [pynamodb/PynamoDB#517]
Hello. I was wondering how does `MapAttribute` of `MapAttribute` work.
I have the following models:

```py
class List(MapAttribute):
    id = UnicodeAttribute()
    name = UnicodeAttribute()

class MyModel(Model):
    id = UnicodeAttribute(hash_key=True)
    lists = MapAttribute(of=List)
```

So now i'd like to call from the dynamodb but the casting is lost

```py
m = MyModel(id="foo", lists={"bar": List(id="bar", name="baz")})
m.save()
print(type(m.lists["bar"])) # <class 'List'>
m.refresh()
print(type(m.lists["bar"])) # <class 'dict'>
```

Is it a bug or the expected behaviour?

**Comment by jney** [comment]
furthermore, adding a `UnicodeSetAttribute` to `List` as followed:

```py
class List(MapAttribute):
    id = UnicodeAttribute()
    name = UnicodeAttribute()
    products = UnicodeSetAttribute(default=[])
```

generates a deserialisation issue:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pynamodb/models.py", line 471, in refresh
    self._deserialize(item_data)
  File "/usr/local/lib/python3.7/site-packages/pynamodb/models.py", line 1309, in _deserialize
    value = attr.deserialize(value)
  File "/usr/local/lib/python3.7/site-packages/pynamodb/attributes.py", line 811, in deserialize
    deserialized_value = attr_class.deserialize(attr_value)
  File "/usr/local/lib/python3.7/site-packages/pynamodb/attributes.py", line 806, in deserialize
    attr_class = self._get_deserialize_class(key, v)
  File "/usr/local/lib/python3.7/site-packages/pynamodb/attributes.py", line 845, in _get_deserialize_class
    return _get_class_for_deserialize(value)
  File "/usr/local/lib/python3.7/site-packages/pynamodb/attributes.py", line 858, in _get_class_for_deserialize
    raise ValueError('Unknown value: ' + str(value))
ValueError: Unknown value: {'SS': ['some string']}
```

**Comment by tomateos** [comment]
Hi @jney, MapAttribute serializes/deserializes your custom object as JSON, which is why you're getting dicts and lists.

I might be missing something, but is there a reason you aren't using ListAttribute? Generally if you want a collection of some attribute, it makes more sense to have a list. A MapAttribute is just a way to serialize objects. With the code you've provided it makes more sense to do this:

```python
class MyList(MapAttribute):
    id = UnicodeAttribute()
    name = UnicodeAttribute()

class MyModel(Model):
    id = UnicodeAttribute()
    lists = ListAttribute(of=MyList)
```

**Comment by jney** [comment]
> MapAttribute serializes/deserializes your custom object as JSON, that might be why your List is being cast as a dict?

`MapAttribute` serialize correctly the object as a [Map](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html#DDB-Type-AttributeValue-M). The issue is about the deserialization (dynamodb record -> python)

> I might be missing something, but is there a reason you aren't using ListAttribute?

I want a quicker (or let's tell easier) access to the data, without having to loop over it finding some object
