### ISSUE TITLE
Custom atrributes default value not being set

### ISSUE THREAD

**Issue by abhyuditjain** [pynamodb/PynamoDB#734]
I have this model:

```
import os
from datetime import datetime

from pynamodb.constants import STRING
from pynamodb.attributes import (
    BooleanAttribute, UnicodeAttribute, UTCDateTimeAttribute, Attribute)
from pynamodb.models import Model

class DateAttribute(Attribute):
    attr_type = STRING
    date_format = '%Y-%m-%d'

    def serialize(self, value):
        self.name = value.strftime(self.date_format)

    def deserialize(self, value):
        return datetime.strptime(value, self.date_format)


class Song(Model):
    class Meta:
        table_name = os.getenv('DYNAMO_DB_TABLE')
        region = os.getenv('AWS_REGION')

    song_id = UnicodeAttribute(hash_key=True, null=False)
    label = UnicodeAttribute(null=False)
    e_tag = UnicodeAttribute(null=False)
    bucket = UnicodeAttribute(null=False)
    key = UnicodeAttribute(null=False)
    hls_completed = BooleanAttribute(default=False, null=False)
    mp4_completed = BooleanAttribute(default=False, null=False)
    mp3_completed = BooleanAttribute(default=False, null=False)
    synced = BooleanAttribute(default=False, null=False)
    job_date = DateAttribute(
        null=False, default=datetime.utcnow())
    created_at = UTCDateTimeAttribute(
        null=False, default=datetime.utcnow())
    updated_at = UTCDateTimeAttribute(null=False)

    def save(self, conditional_operator=None, **expected_values):
        try:
            self.updated_at = datetime.utcnow()
            super(Song, self).save()
        except Exception as e:
            print(e)
            raise e

    def __iter__(self):
        for name, attr in self.get_attributes().items():
            yield name, attr.serialize(getattr(self, name))


songArgs = {'song_id': 'asdas', 'label': 'asdasdasdas', 'e_tag': '123', 'bucket': 'bucket', 'key': 'key'}
song = Song(**songArgs)
song.save()
```

I get this error:

```
Attribute 'job_date' cannot be None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/b0214344/Code/code/common/song.py", line 64, in save
    raise e
  File "/Users/b0214344/Code/code/common/song.py", line 61, in save
    super(Song, self).save()
  File "/Users/b0214344/Envs/code/lib/python3.7/site-packages/pynamodb/models.py", line 394, in save
    args, kwargs = self._get_save_args()
  File "/Users/b0214344/Envs/code/lib/python3.7/site-packages/pynamodb/models.py", line 913, in _get_save_args
    serialized = self._serialize(null_check=null_check)
  File "/Users/b0214344/Envs/code/lib/python3.7/site-packages/pynamodb/models.py", line 1083, in _serialize
    serialized = self._serialize_value(attr, value, null_check)
  File "/Users/b0214344/Envs/code/lib/python3.7/site-packages/pynamodb/models.py", line 1115, in _serialize_value
    raise ValueError("Attribute '{}' cannot be None".format(attr.attr_name))
ValueError: Attribute 'job_date' cannot be None
```

**Comment by ikonst** [comment]
You have to change:
```
    def serialize(self, value):
        self.name = value.strftime(self.date_format)
```
to
```
    def serialize(self, value):
        return value.strftime(self.date_format)
```

Also, unrelated, you should replace:
```
job_date = UTCDateTimeAttribute(null=False, default=datetime.utcnow())
```
with
```
job_date = UTCDateTimeAttribute(null=False, default=datetime.utcnow)
```
The former calls `datetime.utcnow()` immediately when you declare your class, so the default value would be the time when your module was loaded. By passing a function instead (`datetime.utcnow`), you'd be getting the actual current time.

Finally, there's a slight gotcha with Python, in that you cannot compare timezone-aware and naive datetimes. When you'll load your model from a table, you'd have a timezone-aware UTC datetime, so e.g.
```
>>> from datetime import datetime, timezone
>>> assert song.job_date > datetime(2019, 1, 1)
>>> song.save()
>>> song = Song.get(song_id)
>>> assert song.job_date > datetime(2019, 1, 1)
TypeError: can't compare offset-naive and offset-aware datetimes
```

For this reason, on the off chance that you ever might run equation or comparison with the date fields on a model that's been initialized in your code (rather than loaded from a table), it's best to use `default=lambda: datetime.now(tzinfo=timezone.utc)` instead of `default=datetime.utcnow`.

**Comment by abhyuditjain** [comment]
@ikonst I tried what you suggested but I get the following error now:

```
>>> Song.create_table(read_capacity_units=1, write_capacity_units=1)
>>> songArgs = {'song_id': 'abhyuditjain', 'label': 'abhyudit', 'e_tag': '123', 'bucket': 'bucket', 'key': 'key'}
>>> song = Song(**songArgs)
>>> song.save()
object of type 'datetime.datetime' has no len()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/carb0n/Code/asd/common/song.py", line 48, in save
    raise e
  File "/home/carb0n/Code/asd/common/song.py", line 45, in save
    super(Song, self).save()
  File "/home/carb0n/.virtualenvs/asd/lib/python3.7/site-packages/pynamodb/models.py", line 394, in save
    args, kwargs = self._get_save_args()
  File "/home/carb0n/.virtualenvs/asd/lib/python3.7/site-packages/pynamodb/models.py", line 913, in _get_save_args
    serialized = self._serialize(null_check=null_check)
  File "/home/carb0n/.virtualenvs/asd/lib/python3.7/site-packages/pynamodb/models.py", line 1083, in _serialize
    serialized = self._serialize_value(attr, value, null_check)
  File "/home/carb0n/.virtualenvs/asd/lib/python3.7/site-packages/pynamodb/models.py", line 1111, in _serialize_value
    serialized = attr.serialize(value)
  File "/home/carb0n/.virtualenvs/asd/lib/python3.7/site-packages/pynamodb/attributes.py", line 418, in serialize
    if value is None or not len(value):
TypeError: object of type 'datetime.datetime' has no len()
```

**Comment by abhyuditjain** [comment]
@ikonst Also, using `created_at = UnicodeAttribute(null=False, default=lambda: datetime.now(tzinfo=timezone.utc))` gives this error:

```
TypeError: 'tzinfo' is an invalid keyword argument for now()
```

**Comment by ikonst** [comment]
^ You're right of course :)

**Comment by ikonst** [comment]
You're trying to use UnicodeAttribue to serialize a `datetime`.

Change:
```
    created_at = UnicodeAttribute(
```
to
```
    created_at = DateAttribute(
```
