### ISSUE TITLE
How to update an attribute in a ListAttribute of MapAttribute?

### ISSUE THREAD

**Issue by marzigolbaz** [pynamodb/PynamoDB#813]
I am learning how to use PynamoDB to work with AWS DynamoDB in my Python code. Here is what I have defined so far:

```
class OfficeEmployeeMap(MapAttribute):
    office_employee_id = NumberAttribute(hash_key=True)
    office_employee_direct_ids = UnicodeSetAttribute()

class Office(Model):
    class Meta:
        table_name = 'OfficeModel'
    office_id = NumberAttribute(hash_key=True)
    employees = ListAttribute(of=OfficeEmployeeMap)

Office.create_table(read_capacity_units=1, write_capacity_units=1) 
```

Here is how I appended to the list of map attributes (`employees`):

```
emp1 = OfficeEmployeeMap(
    office_employee_id=111,
    office_employee_direct_ids={"222"}
)

Office(
    office_id=1
).update(
    actions=[
        Office.employees.set((Office.employees|[]).append([emp1]))
    ]
)
```

And here is what I am seeing in the newly created DynamoDB table OfficeModel:

![image](https://user-images.githubusercontent.com/10997397/87453538-7886ab00-c5b7-11ea-993b-4aebc8f003e3.png)

Now I need to add another value, like `333`, to the set `office_employee_direct_ids` where `office_employee_id` == `111`, how can I do it with PynamoDB?

**Comment by marzigolbaz** [comment]
@ikonst can you please help? this is blocking me.

**Comment by ikonst** [comment]
@yelizariev You've been looking at this recently. Would have some time to advice?

**Comment by marzigolbaz** [comment]
Tried this code:

```
TestPyDB(
    dict_name='host_vuln_plugin_dict'
).update(
    actions=[
        TestPyDB.host_vuln_plugin_dict[0].host_vuln_v_id.add({"hv2"})
    ],
    condition=(
        (TestPyDB.host_vuln_plugin_dict[0].plugin_id == '123')
    )
)
```
It did raise this error:

```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
AttributeError: 'Path' object has no attribute 'host_vuln_v_id'
```

**Comment by marzigolbaz** [comment]
Tried this code:

```
Office(
    office_id=1
).update(
    actions=[
        Office.employees[0].office_employee_direct_ids.add({"333"})
    ],
    condition=(
        (Office.employees[0].office_employee_id == '111')
    )
) 
```
But, I got this error:

```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
AttributeError: 'Path' object has no attribute 'office_employee_direct_ids'
```
Any reason why I can't access index `0` of the list attribute? 

@ikonst @yelizariev

**Comment by ikonst** [comment]
Following @yelizariev 's example, the code in your first question should be rewritten as:
```python
Office(
    office_id=1
).update(
    actions=[
        Office.employees.set(
            Office.employees.append([emp1])
        )
    ]
)
```

As for the second question, I think you need to use a "getitem" operator, i.e.
```
Office.employees[0]['office_employee_direct_ids'].add({"333"})
```

**Comment by marzigolbaz** [comment]
@ikonst Thanks for your response, getting this error: 

```
>>> Office(
...     office_id=1
... ).update(
...     actions=[
...         Office.employees.set(
...             Office.employees.append([emp1])
...         )
...     ]
... )
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/Users/mgolbaz/Documents/Projects/kraken/venv/lib/python3.7/site-packages/pynamodb/models.py", line 396, in update
    data = self._get_connection().update_item(*args, **kwargs)
  File "/Users/mgolbaz/Documents/Projects/kraken/venv/lib/python3.7/site-packages/pynamodb/connection/table.py", line 118, in update_item
    return_values=return_values)
  File "/Users/mgolbaz/Documents/Projects/kraken/venv/lib/python3.7/site-packages/pynamodb/connection/base.py", line 944, in update_item
    six.raise_from(UpdateError("Failed to update item: {}".format(e), e), None)
  File "<string>", line 3, in raise_from
pynamodb.exceptions.UpdateError: Failed to update item: An error occurred (ValidationException) on request (AQCF371UUQU0IPM0S0VPC5K9VBVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (OfficeModel) when calling the UpdateItem operation: The provided expression refers to an attribute that does not exist in the item
```

**Comment by marzigolbaz** [comment]
@ikonst also tried these, and am getting these errors:

```>>> Office(
...     office_id=1
... ).update(
...     actions=[
...         Office.employees[0]['office_employee_direct_ids'].add({"333"})
...     ]
... ) 
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Users/mgolbaz/Documents/Projects/kraken/venv/lib/python3.7/site-packages/pynamodb/expressions/operand.py", line 286, in add
    return AddAction(self, self._to_operand(value))
  File "/Users/mgolbaz/Documents/Projects/kraken/venv/lib/python3.7/site-packages/pynamodb/expressions/update.py", line 57, in __init__
    subset._type_check(BINARY_SET_SHORT, NUMBER_SET_SHORT, NUMBER_SHORT, STRING_SET_SHORT)
  File "/Users/mgolbaz/Documents/Projects/kraken/venv/lib/python3.7/site-packages/pynamodb/expressions/operand.py", line 48, in _type_check
    raise ValueError("The data type of '{}' must be one of {}".format(self, list(types)))
ValueError: The data type of '{'L': [{'S': '333'}]}' must be one of ['BS', 'NS', 'N', 'SS']
>>> Office(
...     office_id=1
... ).update(
...     actions=[
...         Office.employees[0]['office_employee_direct_ids'].add("333")
...     ]
... )
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Users/mgolbaz/Documents/Projects/kraken/venv/lib/python3.7/site-packages/pynamodb/expressions/operand.py", line 286, in add
    return AddAction(self, self._to_operand(value))
  File "/Users/mgolbaz/Documents/Projects/kraken/venv/lib/python3.7/site-packages/pynamodb/expressions/update.py", line 57, in __init__
    subset._type_check(BINARY_SET_SHORT, NUMBER_SET_SHORT, NUMBER_SHORT, STRING_SET_SHORT)
  File "/Users/mgolbaz/Documents/Projects/kraken/venv/lib/python3.7/site-packages/pynamodb/expressions/operand.py", line 48, in _type_check
    raise ValueError("The data type of '{}' must be one of {}".format(self, list(types)))
ValueError: The data type of '{'S': '333'}' must be one of ['BS', 'NS', 'N', 'SS']
```

**Comment by ikonst** [comment]
Ohh, you were totally right about `Office.employees|[]` :)

**Comment by ikonst** [comment]
I've looked at the code and tbh I'm not sure how it should work, in particular with regard to this line:
https://github.com/pynamodb/PynamoDB/blob/8d58d2e20245a7d0f3d2fb57c9b9760c40ac77c4/pynamodb/expressions/operand.py#L297

It looks like even if you'd pass `{'SS': '333'}` it'd just result in a key error.

Perhaps try:

```
from pynamodb.expressions.update import AddAction
from pynamodb.expressions.operand import Path, Value

pynamodb.expressions.update.AddAction(
   Office.employees[0]['office_employee_direct_ids'],
   Path(Value({'SS': '333'})),
)
```

If this works, then it's definitely not how it's _supposed_ to work and we should fix it.

If it doesn't work, then I'll look into it a bit later.

**Comment by marzigolbaz** [comment]
@ikonst It doesn't work :(. See: 

```
>>> AddAction(
...    Office.employees[0]['office_employee_direct_ids'],
...    Path(Value({'SS': '333'})),
... )
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/mgolbaz/Documents/Projects/kraken/venv/lib/python3.7/site-packages/pynamodb/expressions/operand.py", line 240, in __init__
    super(Path, self).__init__(get_path_segments(path))
  File "/Users/mgolbaz/Documents/Projects/kraken/venv/lib/python3.7/site-packages/pynamodb/expressions/util.py", line 8, in get_path_segments
    return document_path.split('.') if isinstance(document_path, string_types) else list(document_path)
TypeError: 'Value' object is not iterable
```

**Comment by ikonst** [comment]
How about:
```python
from pynamodb.expressions.update import AddAction
from pynamodb.expressions.operand import Path, Value

pynamodb.expressions.update.AddAction(
   Office.employees[0]['office_employee_direct_ids'],
   Value({'SS': '333'}),
)
```
?

**Comment by jpinner-lyft** [comment]
`AddAction(Office.employees[0]['office_employee_direct_ids'], Value({'SS': ['333']}))`

**Comment by jpinner-lyft** [comment]
There is both a bug in the `add` method and the usability of ListAttributes could be improved.

**Comment by marzigolbaz** [comment]
@ikonst it does not raise and error, but seems like it does not have an impact on the data:

```
AddAction(
...    Office.employees[0]['office_employee_direct_ids'],
...    Value({'SS': '333'}),
... )
employees[0].office_employee_direct_ids {'SS': '333'}
```

See:
![image](https://user-images.githubusercontent.com/10997397/87470759-17b89c00-c5d2-11ea-8fa7-cc4a7a4f2703.png)

**Comment by jpinner-lyft** [comment]
@marzigolbaz can you try again but this time put the value in a list: `{'SS': ['333']}`

**Comment by marzigolbaz** [comment]
@jpinner-lyft same result: 

```
>>> AddAction(
...    Office.employees[0]['office_employee_direct_ids'],
...    Value({'SS': ['333']}),
... )
employees[0].office_employee_direct_ids {'SS': ['333']}
```
![image](https://user-images.githubusercontent.com/10997397/87474319-c1e6f280-c5d7-11ea-98bb-d733602727a2.png)

**Comment by yelizariev** [comment]
I don't know how to do it now, as I used [plain structures](https://github.com/itpp-labs/chatops-docs/blob/321d28b4c1a25cf27bcd1d146ad857806787d0db/opinions-bot/lambda_function.py#L340-L342) only. But it would be nice to support ``of=`` arg for MapAttribute:

Like this
```
class Office(Model):
    class Meta:
        table_name = 'OfficeModel'
    office_id = NumberAttribute(hash_key=True)
    # office_employee_id -> office_employee_direct_ids
    employees = MapAttribute(of=UnicodeSetAttribute)
```

or this

```
class OfficeEmployeeMap(MapAttribute):
    office_employee_direct_ids = UnicodeSetAttribute()
    another_field = ....

class Office(Model):
    class Meta:
        table_name = 'OfficeModel'
    office_id = NumberAttribute(hash_key=True)
    employees = MapAttribute(of=OfficeEmployeeMap)
```
