### ISSUE TITLE
Transaction write failed with Table None

### ISSUE THREAD

**Issue by jl-DaDar** [pynamodb/PynamoDB#816]
Some how we are getting an error when trying to save 2 item in a transaction. If done outside of transaction using regular save, everything works just fine. But when we switch to transaction like the code below. 

```
Traceback (most recent call last):
File "/var/task/apps/user/helpers.py", line 181, in register_new_account
transaction.save(user)
File "/opt/python/lib/python3.7/site-packages/pynamodb/transactions.py", line 23, in __exit__
self._commit()
File "/opt/python/lib/python3.7/site-packages/pynamodb/transactions.py", line 117, in _commit
return_item_collection_metrics=self._return_item_collection_metrics,
File "/opt/python/lib/python3.7/site-packages/pynamodb/connection/base.py", line 1023, in transact_write_items
six.raise_from(TransactWriteError("Failed to write transaction items", e), None)
File "<string>", line 3, in raise_from
pynamodb.exceptions.TransactWriteError: Failed to write transaction items

```

```
       user = User(user_id=sharedlib_utils.base64_unique_id(32),
                    search_idx_hkey=f"{method}::{provider}::{value}",
                    updated=now,
                    created=now,
                    **user_info)

        login = Login(login_id=f"{method}::{provider}::{value}",
                      entity_hierarchy_id=entity.hierarchy,
                      user_id=user.user_id,
                      method=method,
                      provider=provider,
                      value=value,
                      hashed_password=password if password else sharedlib_utils.base64_unique_id(16),
                      login_id_for_user_idx_key=user.user_id,
                      main_id=main_id,
                      secondary_id=secondary_id,
                      updated=now,
                      created=now)

        connection = Connection()
        try:
            with TransactWrite(connection=connection) as transaction:
                transaction.save(login)
                transaction.save(user)
        except TransactWriteError as err:
                print(err.cause)

```

which ever is the 2nd transaction.save would failed with AccessDeniedException because table name somehow turned into None. 

`An error occurred (AccessDeniedException) on request (B3RO5AHB8FM3BO4D4F2IS478LBVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (None) when calling the TransactWriteItems operation:
`

**Comment by jl-DaDar** [comment]
ok we have found the problem, 
transaction failed because region was not specified in the connection. But this was never mentioned in the documentation.

also the table becoming None is still a bug
