### ISSUE TITLE
Dynamic table names and offline tests

### ISSUE THREAD

**Issue by l0b0** [pynamodb/PynamoDB#922]
I'm working on a project which uses DynamoDB in AWS, but not locally. To ensure the tests for this code run fast I've installed pytest-socket and run most of the tests with `--disable-socket`. This way any test which attempts to do any networking will fail, which is excellent.

Now I'm also [trying](https://github.com/linz/geospatial-data-lake/pull/424) to use dynamic resource names (including table names). The actual table names are stored in SSM during deployment, and fetched at runtime. To make sure the table name is only fetched when necessary I've done the following:

```
class MyModel(Model):
    class Meta:
        @property
        @classmethod
        def table_name(cls) -> str:
            return SSM_CLIENT.get_parameter(Name="my_parameter")

        …
```

This makes all the local-only tests pass, but unfortunately the acceptance tests fail:

```
tests/test_import_status_endpoint.py:87: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/aws_utils.py:201: in __enter__
    self._item.save()
.venv/lib/python3.8/site-packages/pynamodb/models.py:438: in save
    data = self._get_connection().put_item(*args, **kwargs)
.venv/lib/python3.8/site-packages/pynamodb/connection/table.py:150: in put_item
    return self.connection.put_item(
.venv/lib/python3.8/site-packages/pynamodb/connection/base.py:1011: in put_item
    operation_kwargs = self.get_operation_kwargs(
.venv/lib/python3.8/site-packages/pynamodb/connection/base.py:903: in get_operation_kwargs
    operation_kwargs.update(self.get_identifier_map(table_name, hash_key, range_key, key=key))
.venv/lib/python3.8/site-packages/pynamodb/connection/base.py:820: in get_identifier_map
    tbl = self.get_meta_table(table_name)
.venv/lib/python3.8/site-packages/pynamodb/connection/base.py:548: in get_meta_table
    data = self.dispatch(DESCRIBE_TABLE, operation_kwargs)
.venv/lib/python3.8/site-packages/pynamodb/connection/base.py:329: in dispatch
    data = self._make_api_call(operation_name, operation_kwargs, settings)
.venv/lib/python3.8/site-packages/pynamodb/connection/base.py:358: in _make_api_call
    request_dict = self.client._convert_to_request_dict(
.venv/lib/python3.8/site-packages/botocore/client.py:696: in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
.venv/lib/python3.8/site-packages/botocore/serialize.py:349: in serialize_to_request
    serialized['body'] = json.dumps(body).encode(self.DEFAULT_ENCODING)
../../.pyenv/versions/3.8.6/lib/python3.8/json/__init__.py:231: in dumps
    return _default_encoder.encode(obj)
../../.pyenv/versions/3.8.6/lib/python3.8/json/encoder.py:199: in encode
    chunks = self.iterencode(o, _one_shot=True)
../../.pyenv/versions/3.8.6/lib/python3.8/json/encoder.py:257: in iterencode
    return _iterencode(o, 0)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <json.encoder.JSONEncoder object at 0x7f3bac95c3d0>, o = <property object at 0x7f3baa8194a0>

    def default(self, o):
        """Implement this method in a subclass such that it returns
        a serializable object for ``o``, or calls the base implementation
        (to raise a ``TypeError``).
    
        For example, to support arbitrary iterators, you could
        implement default like this::
    
            def default(self, o):
                try:
                    iterable = iter(o)
                except TypeError:
                    pass
                else:
                    return list(iterable)
                # Let the base class default method raise the TypeError
                return JSONEncoder.default(self, o)
    
        """
>       raise TypeError(f'Object of type {o.__class__.__name__} '
                        f'is not JSON serializable')
E       TypeError: Object of type property is not JSON serializable

../../.pyenv/versions/3.8.6/lib/python3.8/json/encoder.py:179: TypeError
```

What would you suggest to lazy load the table name? I don't want to do something like `table_name = if production then SSM_CLIENT.get_parameter(Name="my_parameter") else ""`, since that introduces a test-only branch.

**Comment by CloudySnake** [comment]
For local AWS mocking I use Moto. It does a very good job of pretending to be all manner of AWS services.

**Comment by l0b0** [comment]
I've also tried

```
        def __getattribute__(self, name: str) -> Any:
            if name == "table_name":
                return SSM_CLIENT.get_parameter(Name="my_parameter")
            return super().__getattribute__(name)
```

and

```
        def __new__(cls) -> Any:
            klass = super().__new__(cls)
            klass.table_name = get_param(ParameterName.DATASETS_TABLE_NAME)
            return klass
```

Both result in

> AttributeError: As of v1.0 PynamoDB Models must have a table_name

**Comment by l0b0** [comment]
A working but really ugly solution is to set `MyModel.Meta.table_name = SSM_CLIENT.get_parameter(Name="my_parameter")` in the production and acceptance test code at runtime.

**Comment by raffienficiaud** [comment]
The simplest solution I've found for this is to wrap the model into a function, something like this. This works not only for the table names but also for the region, which I want inferred from eg. the task definition:

```
class MyModelBase(Model):
    key = UnicodeAttribute(hash_key=True)

    # ...


def get_mymodel(table_name=None, region=None) -> Type[MyModelBase]:
    """Returns the model

    :param table_name: name of the DynamoDB table for the my model
    :param region: AWS region of the DynamoDB table

    If not specified, `table_name` and `region` are taken from the default configuration.

    """
    dynamo_db_table_name, dynamodb_region = "abc", "us-east-1"

   # some work here for the final values of dynamo_db_table_name and dynamodb_region

    class MyConcreteModel(MyModelBase):
        class Meta:
            table_name = dynamo_db_table_name
            region = dynamodb_region
```

There is nothing fancy in this code, it just works and pretty well adapted to tests (moto and localstack).

**Comment by l0b0** [comment]
Thank you @raffienficiaud, this got me close to a working solution. I can't get it to work with any indexes though. The first attempt:

```python
class ValidationResultsModelBase(Model):
    pk = UnicodeAttribute(hash_key=True)
    sk = UnicodeAttribute(range_key=True)
    result = UnicodeAttribute()
    # TODO: Remove type-arg when https://github.com/pynamodb/PynamoDB/issues/682 is fixed
    details: MapAttribute = MapAttribute(null=True)  # type: ignore[type-arg]

    validation_outcome_index = ValidationOutcomeIdx()


def validation_results_model_with_meta() -> Type[ValidationResultsModelBase]:
    class ValidationResultsModel(ValidationResultsModelBase):
        class Meta:  # pylint:disable=too-few-public-methods
            table_name = get_param(ParameterName.VALIDATION_RESULTS_TABLE_NAME)
            region = environ["AWS_DEFAULT_REGION"]

    return ValidationResultsModel
```

Second attempt:

```python
class ValidationResultsModelBase(Model):
    pk = UnicodeAttribute(hash_key=True)
    sk = UnicodeAttribute(range_key=True)
    result = UnicodeAttribute()
    # TODO: Remove type-arg when https://github.com/pynamodb/PynamoDB/issues/682 is fixed
    details: MapAttribute = MapAttribute(null=True)  # type: ignore[type-arg]


def validation_results_model_with_meta() -> Type[ValidationResultsModelBase]:
    class ValidationResultsModel(ValidationResultsModelBase):
        class Meta:  # pylint:disable=too-few-public-methods
            table_name = get_param(ParameterName.VALIDATION_RESULTS_TABLE_NAME)
            region = environ["AWS_DEFAULT_REGION"]

        validation_outcome_index = ValidationOutcomeIdx()

    return ValidationResultsModel
```

Both of these result in

```
[ERROR] AttributeError: type object 'ValidationResultsModelBase' has no attribute 'Meta'
Traceback (most recent call last):
  File "/var/task/backend/validation_summary/task.py", line 29, in lambda_handler
    validation_results_model.validation_outcome_index.count(
  File "/var/task/pynamodb/indexes.py", line 70, in count
    return cls.Meta.model.count(
  File "/var/task/pynamodb/models.py", line 584, in count
    cls._get_indexes()
  File "/var/task/pynamodb/models.py", line 907, in _get_indexes
    if getattr(cls.Meta, 'billing_mode', None) != PAY_PER_REQUEST_BILLING_MODE:
```

I'm not sure how to progress - is there an official pattern for implementing this?

**Comment by l0b0** [comment]
I think I've found a way to do this with an intermediate `MetaModel`, based on [this](https://github.com/pynamodb/PynamoDB/issues/247#issuecomment-288217078) and [this](https://github.com/pynamodb/PynamoDB/issues/287#issuecomment-613059240). The difference from those examples is the index, which must be declared *after* `Meta`, and therefore is set in the function which creates a decorated model class:

```python
class DatasetsTitleIdx(
    GlobalSecondaryIndex["DatasetsModelBase"]
):  # pylint:disable=too-few-public-methods,inherit-non-class
    pass # Set up Meta and fields


class DatasetsModelBase(Model):
    # Set up fields and methods

    # Type annotate any indexes for mypy
    datasets_title_idx: DatasetsTitleIdx


class DatasetsModelMeta(MetaModel):
    def __new__(
        cls,
        name: str,
        bases: Tuple[Type[object], ...],
        namespace: Dict[str, Any],
        discriminator: Optional[Any] = None,
    ) -> "DatasetsModelMeta":
        namespace["Meta"] = type(
            "Meta",
            (),
            {
                "table_name": get_param(ParameterName.DATASETS_TABLE_NAME),
                "region": environ["AWS_DEFAULT_REGION"],
            },
        )
        klass: "DatasetsModelMeta" = MetaModel.__new__(
            cls, name, bases, namespace, discriminator=discriminator
        )
        return klass


def datasets_model_with_meta() -> Type[DatasetsModelBase]:
    class DatasetModel(DatasetsModelBase, metaclass=DatasetsModelMeta):
        datasets_title_idx = DatasetsTitleIdx()

    return DatasetModel
```

Now any local tests can use `DatasetsModelBase` and production code uses `datasets_model_with_meta`.

**Comment by ikonst** [comment]
I'd consider mocking SSM with https://github.com/spulec/moto. Assuming "the actual table names are stored in SSM during deployment, and fetched at runtime" is done just to satisfy network-less testing, moto would help.

If you're using pytest, I'd set up a session fixture:
```
@pytest.fixture(scope='session', autouse=True)
def moto_ssm_backend():
    backend = moto.mock_ssm()
    with backend:
        yield backend.backends['us-east-1']
```

**Comment by raffienficiaud** [comment]
@l0b0 I have something like this, I do not like it much, but I like it better than more complicated alternatives:

```python
class MyModelBaseIndex(GlobalSecondaryIndex):

    class MetaBase:
        # name of the index overridden in the child class
        # example of projection
        projection = KeysOnlyProjection()

    attrX = UnicodeAttribute(hash_key=True)


class ModelBase(Model):
    key = UnicodeAttribute(hash_key=True)

    # ... 
    # at this time, model and index are not linked together. They will be in the get_mymodel below

def get_mymodel(table_name=None, region=None) -> Type[MyModelBase]:

    class ConcreteIndexMyModelBaseIndex):
        class Meta(MyModelBaseIndex.MetaBase):
            read_capacity_units = 20
            write_capacity_units = 1

            index_name = table_name + "-xyz_index"

    class MyConcreteModel(MyModelBase):
        class Meta:
            table_name = table_name
            region = region

        #: Index
        gsi_document = ConcreteIndex()
```

The idea here is to delay as much as possible deployment/infra related information such that we can override it at runtime. Unfortunately in the above example, the link between model and index is delayed too while it is integral part of the code (not the infra). But other developers can follow what is happening because it stays quite simple. I would be happier if there is a way to have a better design though.

Side note: I noticed a runtime penalty in instanciating the model at every function call, python3 has a caching decorator that may help (but makes the testing a bit more difficult). A global instance (through some singleton helper class) is another solution that does not have this penalty and is easy to manipulate from the tests.
