### ISSUE TITLE
DynamoDB Query return strange jsva.lang.String exception

### ISSUE THREAD

**Issue by dimavitvickiy** [pynamodb/PynamoDB#945]
DynamoDB Query returns strange exception (Unrecognized collection type class java.lang.String)
Thit is fine if it returns: "when calling the Query operation: Filter Expression can only contain non-primary key attributes: Primary key attribute: ssr_code", which raises for **is_in** operation on sort key, but for **not is_in** operation it returns SerializationException

Query:
```
cls.query(
    service_bundle['serviceBundleCode'],
    filter_condition=~cls.ssr_code.is_in(ssrs_in_bundle)
)
```

Error:
```
  [ERROR] QueryError: Failed to query items: An error occurred (SerializationException) on request (A9Q3NKJL47VVECA89NQ5EULG4FVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (bundle-table) when calling the Query operation: Unrecognized collection type class java.lang.String
    Traceback (most recent call last):
      File "/var/task/bundle_change.py", line 60, in lambda_handler
        bundles = ServiceBundle.store_bundles(message)
      File "/var/task/models.py", line 72, in store_bundles
        bundle_ssrs_to_delete.extend(
      File "/var/task/pynamodb/pagination.py", line 194, in __next__
        self._get_next_page()
      File "/var/task/pynamodb/pagination.py", line 179, in _get_next_page
        page = next(self.page_iter)
      File "/var/task/pynamodb/pagination.py", line 115, in __next__
        page = self._operation(*self._args, settings=self._settings, **self._kwargs)
      File "/var/task/pynamodb/connection/table.py", line 270, in query
        return self.connection.query(
      File "/var/task/pynamodb/connection/base.py", line 1335, in query
        raise QueryError("Failed to query items: 
    {}
    ".format(e), e)
```

Any ideas ?

**Comment by ikonst** [comment]
The error is passing a list to `is_in` rather than the parameters themselves: try `is_in(*ssrs_in_bundle)`. I agree this is confusing and we should've probably handled it better.

**Comment by dimavitvickiy** [comment]
Thank you for the answer

**Comment by ikonst** [comment]
I've fixed the type annotation btw: https://github.com/pynamodb/PynamoDB/pull/947
