### ISSUE TITLE
Difficulties when using UTCDateTimeAttribute()

### ISSUE THREAD

**Issue by jovana** [pynamodb/PynamoDB#955]
I have an interesting case. 

This is a part of my Model setup:
```
class InstagramPluginSettings(MapAttribute):
    instagram_access_token = UnicodeAttribute(null=True)
    instagram_enable = BooleanAttribute(default=False)
    instagram_access_token_date = UTCDateTimeAttribute()
```

When executing an update or save command using the current date:
```
...
"instagram_access_token_date": datetime.datetime.utcnow(),
...
```
it creates nicely a date-time string:
```
 "instagram_access_token_date": {
            "S": "2021-06-26T20:19:14.494658+0000"
          },
```

Now I want to run the update command, and not touching this UTCDateTimeAttribute. It gives me this error:
```
AttributeError: 'str' object has no attribute 'tzinfo'
```
For some reason, it seems not compatible anymore.
I found this in the documentation (but it does not apply in my case because these are newly created DateTime strings):
```
The UTCDateTimeAttribute now strictly requires the date string format ‘%Y-%m-%dT%H:%M:%S.%f%z’ to ensure proper ordering. PynamoDB has always written values with this format but previously would accept reading other formats. Items written using other formats must be rewritten before upgrading.
```
source: https://pynamodb.readthedocs.io/en/latest/release_notes.html?highlight=UTCDateTimeAttribute#v5-0-0

I hope there is some easy explanation for this what I'am doing wrong here :-)

Any help is welcome!

Jo

**Comment by ikonst** [comment]
Can you provide a more complete code sample?

**Comment by jovana** [comment]
Settings model:

```
class InstagramPluginSettings(MapAttribute):
    instagram_access_token = UnicodeAttribute(null=True)
    instagram_enable = BooleanAttribute(default=False)
    instagram_access_token_date = UTCDateTimeAttribute()

class CustomerSettingsDatabaseModel(Model):
    class Meta:
        table_name = "customer-settings"
        region = os.getenv("AWS_REGION")
        billing_mode = "PAY_PER_REQUEST"

    customer_id = UnicodeAttribute(hash_key=True)
    vendor_id = UnicodeAttribute(range_key=True)
    debtor_number_sequence = NumberAttribute(default=0)
    settings_plugin_data = InstagramPluginSettings(null=True)
```

Adding new item
```
            settings = CustomerSettingsDatabaseModel()
            settings.customer_id = new_customer_id
            settings.vendor_id = new_vendor_id
            settings_plugin_data = {
                                "instagram_access_token": instagram_access_token,
                                "instagram_access_token_date": datetime.datetime.utcnow(),
                                "instagram_enable": True
                            }
            settings.save()
```


Output for 
```
 "instagram_access_token_date": {
            "S": "2021-06-26T20:19:14.494658+0000"
          },
```

update something (don't touch the settings_plugin_data object)
```
update_customer_settings = CustomerSettingsDatabaseModel.get(id1, id2)
 update_response = update_customer_settings.update(
                actions=[
                    CustomerSettingsDatabaseModel.debtor_number_sequence.set(5)
                ],
                condition=(CustomerSettingsDatabaseModel.customer_id == id),
            )
```

The above code failed, and gives this error:
```
AttributeError: 'str' object has no attribute 'tzinfo'
```

**Comment by ikonst** [comment]
Can you provide the full stack trace?

**Comment by jovana** [comment]
Thanks for helping me out! 
This is the full trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 188, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 135, in run_endpoint_function
    return await dependant.call(**values)
  File "./application/routers/customer.py", line 181, in customer_update_plugin_settings
    response = customer.customer_plugin_settings_update(data, credentials)
  File "./application/modules/customer/customer.py", line 623, in customer_plugin_settings_update
    CustomerSettingsDatabaseModel.settings_plugin_data.set(merged_dict)
  File "/usr/local/lib/python3.8/site-packages/pynamodb/attributes.py", line 208, in set
    return Path(self).set(value)
  File "/usr/local/lib/python3.8/site-packages/pynamodb/expressions/operand.py", line 283, in set
    return SetAction(self, self._to_operand(value))
  File "/usr/local/lib/python3.8/site-packages/pynamodb/expressions/operand.py", line 45, in _to_operand
    return Path(value) if isinstance(value, Attribute) else self._to_value(value)
  File "/usr/local/lib/python3.8/site-packages/pynamodb/expressions/operand.py", line 328, in _to_value
    return Value(value, attribute=self.attribute)
  File "/usr/local/lib/python3.8/site-packages/pynamodb/expressions/operand.py", line 200, in __init__
    (self.attr_type, value) = Value.__serialize(value, attribute)
  File "/usr/local/lib/python3.8/site-packages/pynamodb/expressions/operand.py", line 221, in __serialize
    return attribute.attr_type, attribute.serialize(value)
  File "/usr/local/lib/python3.8/site-packages/pynamodb/attributes.py", line 942, in serialize
    return AttributeContainer._container_serialize(values, null_check=null_check)
  File "/usr/local/lib/python3.8/site-packages/pynamodb/attributes.py", line 354, in _container_serialize
    attr_value = attr.serialize(value, null_check=null_check)
  File "/usr/local/lib/python3.8/site-packages/pynamodb/attributes.py", line 942, in serialize
    return AttributeContainer._container_serialize(values, null_check=null_check)
  File "/usr/local/lib/python3.8/site-packages/pynamodb/attributes.py", line 356, in _container_serialize
    attr_value = attr.serialize(value)
  File "/usr/local/lib/python3.8/site-packages/pynamodb/attributes.py", line 682, in serialize
    if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'
```

Output of pip freeze command:
```
appdirs==1.4.4
appnope==0.1.2
attrs==21.2.0
autopep8==1.5.6
Babel==2.9.1
backcall==0.2.0
beautifulsoup4==4.9.3
boto3==1.17.102
botocore==1.20.102
cached-property==1.5.2
certifi==2021.5.30
cffi==1.14.5
chardet==4.0.0
cryptography==3.4.7
decorator==5.0.9
defusedxml==0.7.1
dnspython==2.1.0
ecdsa==0.17.0
email-validator==1.1.3
fastapi==0.65.2
idna==2.10
ipdb==0.13.9
ipython==7.25.0
ipython-genutils==0.2.0
isodate==0.6.0
jedi==0.18.0
jmespath==0.10.0
lxml==4.6.3
mailchimp-marketing==3.0.51
matplotlib-inline==0.1.2
mollie-api-python==2.8.0
oauthlib==3.1.1
parso==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.2.0
prompt-toolkit==3.0.19
ptyprocess==0.7.0
pyasn1==0.4.8
pycodestyle==2.7.0
pycparser==2.20
pydantic==1.8.2
Pygments==2.9.0
pynamodb==5.1.0
pyOpenSSL==20.0.1
python-dateutil==2.8.1
python-dotenv==0.18.0
python-jose==3.3.0
python-multipart==0.0.5
pytz==2021.1
requests==2.25.1
requests-file==1.5.1
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
rsa==4.7.2
s3transfer==0.4.2
simplejson==3.17.2
six==1.16.0
soupsieve==2.2.1
starlette==0.14.2
toml==0.10.2
traitlets==5.0.5
typing-extensions==3.10.0.0
urllib3==1.26.6
wcwidth==0.2.5
xmlsec==1.3.11
zeep==4.0.0
```

**Comment by ikonst** [comment]
In your stack trace I'm seeing:
```
CustomerSettingsDatabaseModel.settings_plugin_data.set(merged_dict)
```

How does `merged_dict` get created?

**Comment by jovana** [comment]
Okay, merged_dict is the output from the database ( .get() )converted to json. The code needs to check if the object exists in the database or not. 

```
        update_customer_settings = CustomerSettingsDatabaseModel.get(id, id)
        update_data = CustomerPluginSettings(**data.__dict__)
        current_dict = json.loads(update_customer_settings.toJSON())

        if not "settings_plugin_data" in current_dict:
           # Add new object
            current_dict['settings_plugin_data'] = {}
        
       # Save current plugin data dict
        merged_dict = {**current_dict['settings_plugin_data']}

        # rebuild a new object item and adding new data into it.
        for plugin in update_data.plugin_data:
            if len(current_dict['settings_plugin_data']) > 0:
                if plugin in current_dict['settings_plugin_data']:
                    merged_dict[plugin] = {**current_dict['settings_plugin_data'][plugin], **update_data.plugin_data[plugin]}
                else:
                    merged_dict[plugin] = {**update_data.plugin_data[plugin]}
            else:
                merged_dict[plugin] = {**update_data.plugin_data[plugin]}
            
            update_customer_settings.update(
                actions=[CustomerSettingsDatabaseModel.settings_plugin_data.set(merged_dict)]
        )
```

**Comment by jovana** [comment]
> Okay, merged_dict is the output from the database ( .get() )converted to json. The code needs to check if the object exists in the database or not.
> 
> ```
>         update_customer_settings = CustomerSettingsDatabaseModel.get(id, id)
>         update_data = CustomerPluginSettings(**data.__dict__)
>         current_dict = json.loads(update_customer_settings.toJSON())
> 
>         if not "settings_plugin_data" in current_dict:
>            # Add new object
>             current_dict['settings_plugin_data'] = {}
>         
>        # Save current plugin data dict
>         merged_dict = {**current_dict['settings_plugin_data']}
> 
>         # rebuild a new object item and adding new data into it.
>         for plugin in update_data.plugin_data:
>             if len(current_dict['settings_plugin_data']) > 0:
>                 if plugin in current_dict['settings_plugin_data']:
>                     merged_dict[plugin] = {**current_dict['settings_plugin_data'][plugin], **update_data.plugin_data[plugin]}
>                 else:
>                     merged_dict[plugin] = {**update_data.plugin_data[plugin]}
>             else:
>                 merged_dict[plugin] = {**update_data.plugin_data[plugin]}
>             
>             update_customer_settings.update(
>                 actions=[CustomerSettingsDatabaseModel.settings_plugin_data.set(merged_dict)]
>         )
> ```

Oops I forgot to mention: the function .toJSON() (on line 3 in above code). I have used the ModelEncoder from this issue: 
https://github.com/pynamodb/PynamoDB/issues/152

**Comment by ikonst** [comment]
That's a pretty big chunk of code you omitted from your initial report :)

If you're doing:
```python
CustomerSettingsDatabaseModel.settings_plugin_data.set({ ..., "instagram_access_token_date": "<date string>", ... })
```
then - yes, you'd get this error you're seeing, because you're supposed to pass a `datetime`, not ` str`.

**Comment by jovana** [comment]
> That's a pretty big chunk of code you omitted from your initial report :)
> 
> If you're doing:
> 
> ```python
> CustomerSettingsDatabaseModel.settings_plugin_data.set({ ..., "instagram_access_token_date": "<date string>", ... })
> ```
> 
> then - yes, you'd get this error you're seeing, because you're supposed to pass a `datetime`, not ` str`.

Yeah, sorry for that. I wanted the have the code clean and readable. But okay good point! I wasn't aware of the convertion to a string. Thanks for take a look and pointing me in the right direction. I will close this now :-)

thx!

**Comment by adminy** [comment]
Still getting this error on the latest version:
```
    workspace.save()
.venv/lib/python3.10/site-packages/pynamodb/models.py:457: in save
    args, kwargs = self._get_save_args(condition=condition, add_version_condition=add_version_condition)
.venv/lib/python3.10/site-packages/pynamodb/models.py:928: in _get_save_args
    attribute_values = self.serialize(null_check)
.venv/lib/python3.10/site-packages/pynamodb/models.py:1149: in serialize
    return self._container_serialize(null_check=null_check)
.venv/lib/python3.10/site-packages/pynamodb/attributes.py:358: in _container_serialize
    attr_value = attr.serialize(value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pynamodb.attributes.UTCDateTimeAttribute object at 0x7f8de6114370>, value = '2023-07-17T00:00:00+00:00'

    def serialize(self, value):
        """
        Takes a datetime object and returns a string
        """
>       if value.tzinfo is None:
E       AttributeError: 'str' object has no attribute 'tzinfo'

.venv/lib/python3.10/site-packages/pynamodb/attributes.py:714: AttributeError
```

**Comment by jovana** [comment]
> Still getting this error on the latest version:
> 
> ```
>     workspace.save()
> .venv/lib/python3.10/site-packages/pynamodb/models.py:457: in save
>     args, kwargs = self._get_save_args(condition=condition, add_version_condition=add_version_condition)
> .venv/lib/python3.10/site-packages/pynamodb/models.py:928: in _get_save_args
>     attribute_values = self.serialize(null_check)
> .venv/lib/python3.10/site-packages/pynamodb/models.py:1149: in serialize
>     return self._container_serialize(null_check=null_check)
> .venv/lib/python3.10/site-packages/pynamodb/attributes.py:358: in _container_serialize
>     attr_value = attr.serialize(value)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> self = <pynamodb.attributes.UTCDateTimeAttribute object at 0x7f8de6114370>, value = '2023-07-17T00:00:00+00:00'
> 
>     def serialize(self, value):
>         """
>         Takes a datetime object and returns a string
>         """
> >       if value.tzinfo is None:
> E       AttributeError: 'str' object has no attribute 'tzinfo'
> 
> .venv/lib/python3.10/site-packages/pynamodb/attributes.py:714: AttributeError
> ```
Hi, I made this mistake also, but you're supposed to pass a datetime object, not  str.
